install.packages("gtrendsR")
library("gtrendsR")

#Clear workspace memory
rm(list=ls())

## Search terms
A <- c("Computer",
       "vakantie",
       "Accomodatie",
       "Accommodatie",
       "Bestemmingen",
       "Nieuwe Auto",
       "Zonnepanelen",
       "Hypotheek aflossen",
       "Makelaar",
       "Promotie",
       "Vacature",
       "Faillissement",
       "Vervroegd pensioen",
       "Goud",
       "Aandelen",
       "Winkelen",
       "Wasmachine",
       "Restaurant",
       "Uiteten",
       "Golf",
       "Inflatie",
       "Rente",
       "Recessie",
       "Olie",
       "Wintersport",
       "Hotel",
       "Weekendje weg",
       "Overnachting",
       "Hostel",
       "Tesla",
       "Mercedes",
       "Porsche",
       "Volkswagen",
       "Auto verkopen",
       "Auto huren",
       "vacaturebank",
       "Werkloosheid",
       "WW",
       "UWV",
       "Uitkering",
       "werkloosheidsuitkering",
       "Beurs",
       "Investeren",
       "tweede huis kopen",
       "Ikea",
       "meubels",
       "Aandelenmarkt",
       "Electronica",
       "Televisie",
       "Sieraden",
       "Tommy Hillfiger",
       "Burberry",
       "Lacoste",
       "Armani",
       "Versace",
       "Ralph Lauren",
       "Chanel",
       "Prada",
       "Hermes",
       "Gucci",
       "Louis Vuitton",
       "Stone Island",
       "Bijenkorf",
       "Hudson Bay",
       "Uit eten",
       "Golfbrevet",
       "handicap golf",
       "golfbanen nederland",
       "golfbanen",
       "vliegbrevet",
       "Schiphol",
       "skyscanner",
       "goedkoop vliegen",
       "businessclass",
       "vliegtuig",
       "beleggen",
       "zelf beleggen",
       "spaarrekening",
       "rentes vergelijken",
       "bedrijf oprichten",
       "kamer van koophandel",
       "eenmanszaak",
       "zelfstandig zonder personeel",
       "ZZP",
       "ontslagrecht",
       "baanzekerheid",
       "verzekering",
       "ziektekosten",
       "start-up",
       "techhub",
       "Brightlands",
       "PVV",
       "CDA",
       "VVD",
       "PVDA",
       "D66",
       "ChristenUnie",
       "GroenLinks",
       "SGP",
       "Partij voor de Dieren",
       "Denk",
       "Forum voor Democratie",
       "DENK",
       "Albert Heijn Bonus",
       "Jumbo aanbiedingen",
       "Aldi aanbiedingen",
       "Lidl",
       "Supermarkt Bonus",
       "Schuldsanering Nederland",
       "Schulden aflossen Nederland",
       "Voedselbank",
       "Kortingen winkels",
       "hulp met geld besparen")

## X maken, heeft 120 columns en 261 rijen nodig. Dates ranging from 2012-12-02 to 2017-11-26
P = 119
N = 261
X <- matrix(data = NA, nrow = N, ncol = P)
for(i in 1:P)
{
  X[,i] <- gtrends(A[i],geo = "NL")$interest_over_time[,2]
}

## Standardize variables?
